api/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from djgeojson.views import GeoJSONLayerView

from sights.models import Place, Territory, Municipality
from .views import TiledGeoJSONData, placeasgeojson, AllUserAutocomplete, ActiveUserAutocomplete, MunicipalityAutocomplete, TerritoryAutocomplete, TaxaAutocomplete

urlpatterns = [
    # url(r'^place.geojson$',
    #     login_required(GeoJSONLayerView.as_view(model=Place, properties=('name', 'pk', 'municipality'), simplify=0.5)),
    #     name='geodata_place'),
    url(r'^municipality.geojson$', login_required(
        GeoJSONLayerView.as_view(model=Municipality, precision=3, simplify=0.5, properties=('name', 'code'))),
        name='geodata_municipality'),
    url(r'^territory.geojson$', login_required(
        GeoJSONLayerView.as_view(model=Territory, precision=3, simplify=0.5, properties=('name', 'code'))),
        name='geodata_territory'),
    url(r'^place.geojson$', placeasgeojson, name='geodata_place'),
    url(
        r'^active-user-autocomplete/$',
        ActiveUserAutocomplete.as_view(),
        name='active_user_autocomplete',
    ),
    url(
        r'^all-user-autocomplete/$',
        AllUserAutocomplete.as_view(),
        name='all_user_autocomplete',
    ),
    url(
        r'^taxa-autocomplete/$',
        TaxaAutocomplete.as_view(),
        name='taxa_autocomplete',
    ),
    url(
        r'^municipality-autocomplete/$',
        MunicipalityAutocomplete.as_view(),
        name='municipality_autocomplete',
    ),
    url(
        r'^territory-autocomplete/$',
        TerritoryAutocomplete.as_view(),
        name='territory_autocomplete',
    ),
]

dbchiro/urls.py
from django.conf import settings
from django.conf.urls import url, include, static
from django.contrib.auth import views as auth_views
from django.contrib.auth.urls import views
from django.contrib.gis import admin

admin.autodiscover()
admin.site.index_title = 'Tables de données'
admin.site.site_header = 'Interface de gestion'

urlpatterns = [
                  url(r'^nested_admin/', include('nested_admin.urls')),
                  url(r'^login/$', auth_views.login,
                      {'template_name': 'login.html'}, name='login'),
                  url(r'^logout/$', auth_views.logout,
                      {'template_name': 'logout.html'}, name='logout'),
                  url(r'^password_reset/$', views.PasswordResetView.as_view(), name='password_reset'),
                  url(r'^password_reset/done/$', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
                  url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                      views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
                  url(r'^reset/done/$', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
                  url(r'^admin/', admin.site.urls),
                  url(r'^admin/doc/', include('django.contrib.admindocs.urls'),
                      name='dbgestion_doc'),
                  url(r'', include('core.urls', namespace='core')),
                  url(r'^accounts/', include('accounts.urls', namespace='accounts')),
                  url(r'', include('blog.urls', namespace='blog')),
                  url(r'', include('sights.urls', namespace='sights')),
                  url(r'', include('management.urls', namespace='management')),
                  url(r'^synthesis/', include('synthesis.urls', namespace='synthesis')),
                  url(r'^api/', include('api.urls', namespace='api')),

              ] + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                  url(r'^__debug__/', include(debug_toolbar.urls)),
              ] + urlpatterns

templates/base.html
{% load i18n static %}
{% load cache %}
{% load staticfiles %}
<!doctype html>
<html class="no-js" lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- indiquez ici le titre de votre page -->
  <title>{{ SITE_NAME }} - {{ title }}</title>

	{# Inclusion des CSS principaux #}
	{% include "main/head_main_assets.html" %}

	<style>
		header {
			background: url('{% static 'img/header_background.jpg' %}') no-repeat center;
	    }
	    .leaflet-container-default {
	     	min-height: 500px;
	    }
	</style>
</head>
{% load i18n %}

<body>
	{# Inclusion de la barre de menu en haut de page #}
	{% include "main/topbar.html" %}
	{# Inclusion du header de base #}
	{% include "main/base_header.html" %}
	<div class="row">
		<div class="columns">
			{% block content %}
			{% endblock %}
		</div>
	</div>
	{# Inclusion du footer de base #}
	{% include "main/footer.html" %}
    {% include "main/footer_main_assets.html" %}
</body>

</html>

templates/base_fullwidth_leaflet.html
{% load staticfiles %}
<!doctype html>
<html class="no-js" lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- indiquez ici le titre de votre page -->
  <title>dbChiro[web]</title>
	{# Inclusion des css principaux #}
	{% include "main/head_main_assets.html" %}
	{# Inclusion des css et js LeafLet #}
	{% include "main/head_leaflet.html" %}
  <style>
    header {
      background: url('{% static 'img/header_background.jpg' %}') no-repeat center;
    }

    .leaflet-container-default {
      min-height: 500px;
    }
  </style>
</head>

<body>
	{# Inclusion de la barre de menu en haut de page #}
	{% include "main/topbar.html" %}
	{# Inclusion du header de base #}
	{% include "main/base_header.html" %}
	<div class="row fullWidth">
		<div class="columns">
			{% block content %}
			{% endblock %}
		</div>
	</div>
	{# Inclusion du header de base #}
	{% include "main/footer.html" %}
    {% include "main/footer_main_assets.html" %}
</body>

</html>

templates/base_home.html
{% load staticfiles %}
<!doctype html>
<html class="no-js" lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- indiquez ici le titre de votre page -->
  <title>dbChiro[web]</title>
	{# Inclusion des CSS principaux #}
	{% include "main/head_main_assets.html" %}
	<link rel="stylesheet" href="{% static 'css/app_header_home.css' %}">
  <style>
    header {
      background: url('{% static 'img/header_background.jpg' %}') no-repeat center;
    }

    .leaflet-container-default {
      min-height: 500px;
    }
  </style>
</head>

<body>
	{# Inclusion de la barre de menu en haut de page #}
	{% include "main/topbar.html" %}
	{# Inclusion du header de base #}
	{% include "main/base_header.html" %}
	<div class="row">
{#		<div class="columns">#}
			{% block content %}
			{% endblock %}
{#		</div>#}
	</div>
	{# Inclusion du footer de base #}
	{% include "main/footer.html" %}
    {% include "main/footer_main_assets.html" %}
</body>

</html>

templates/base_leaflet.html
{% load staticfiles %}
<!doctype html>
<html class="no-js" lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- indiquez ici le titre de votre page -->
  <title>dbChiro[web]</title>
	{# Inclusion des css principaux #}
	{% include "main/head_main_assets.html" %}
	{# Inclusion des css et js LeafLet #}
	{% include "main/head_leaflet.html" %}
  <style>
    header {
      background: url('{% static 'img/header_background.jpg' %}') no-repeat center;
    }

    .leaflet-container-default {
      min-height: 500px;
    }
  </style>
</head>

<body>
	{# Inclusion de la barre de menu en haut de page #}
	{% include "main/topbar.html" %}
	{# Inclusion du header de base #}
	{% include "main/base_header.html" %}
	<div class="row">
		<div class="columns">
			{% block content %}
			{% endblock %}
		</div>
	</div>
	{# Inclusion du footer de base #}
	{% include "main/footer.html" %}
    {% include "main/footer_main_assets.html" %}
</body>

</html>

templates/login.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <h1><i class="fa fa-sign-in"></i> Connexion</h1>
    {% if form.errors and not form.non_field_errors %}
        <div class="callout small alert">
            <p class="errornote">
                {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}
                    {% trans "Please correct the errors below." %}{% endif %}
            </p>
        </div>
    {% endif %}

    {% if form.non_field_errors %}
        <div class="callout small alert">
            {% for error in form.non_field_errors %}
                <p class="errornote">
                    {{ error }}
                </p>
            {% endfor %}
        </div>
    {% endif %}

    <div id="content-main">

        {% if user.is_authenticated %}
            <div class="callout small success">
                <p class="errornote">
                    {% blocktrans trimmed %}
                        You are authenticated as {{ username }}, but are not authorized to
                        access this page. Would you like to login to a different account?
                    {% endblocktrans %}
                </p>
            </div>
        {% endif %}

        <form action="{{ app_path }}" method="post" id="login-form">{% csrf_token %}

            <div class="input-group">
                <span class="input-group-label"><i class="fi-torso"></i></span>
                <input class="input-group-field" name="username" type="text" for="username"
                       placeholder="Votre identifiant">
            </div>
            <div class="input-group">
                <span class="input-group-label"><i class="fi-lock"></i></span>
                <input class="input-group-field" name="password" type="password" for="password"
                       placeholder="Votre mot de passe">
                <div class="input-group-button">
                    <input type="submit" class="button" value="{% trans 'Log in' %}">
                </div>
            </div>

                {#            <div class="form-row">#}
                {#                {{ form.username.errors }}#}
                {#                {{ form.username.label_tag }} {{ form.username }}#}
                {#            </div>#}
                {#            <div class="form-row">#}
                {#                {{ form.password.errors }}#}
                {#                {{ form.password.label_tag }} {{ form.password }}#}
                {#                <input type="hidden" name="next" value="{{ next }}"/>#}
                {#            </div>#}
                {% url 'admin_password_reset' as password_reset_url %}
                {% if password_reset_url %}
                    <div class="password-reset-link">
                        <a href="{{ password_reset_url }}">{% trans 'Forgotten your password or username?' %}</a>
                    </div>
                {% endif %}
        </form>

    </div>
{% endblock %}
{##}
{##}
{#{% block content %}#}
{#    <h1><i class="fa fa-sign-in"></i> Connexion</h1>#}
{#    <!--   <form method="post">#}
{#    {% csrf_token %}#}
{#    {{ form.as_p }} -->#}
{#    <div id="login">#}
{#        <form name="LoginForm" action="/login/" method="post">#}
{#            {% csrf_token %} {% if next %}#}
{#            <input type="hidden" name="next" value="{{ next }}"/> {% endif %}#}
{#            <div class="input-group">#}
{#                <span class="input-group-label"><i class="fi-torso"></i></span>#}
{#                <input class="input-group-field" name="username" type="text" for="username"#}
{#                       placeholder="Votre identifiant">#}
{#            </div>#}
{#            <div class="input-group">#}
{#                <span class="input-group-label"><i class="fi-lock"></i></span>#}
{#                <input class="input-group-field" name="password" type="password" for="password"#}
{#                       placeholder="Votre mot de passe">#}
{#                <div class="input-group-button">#}
{#                    <input type="submit" class="button" value="Connexion">#}
{#                </div>#}
{#            </div>#}
{#        </form>#}
{#    </div>#}
{#{% endblock %}#}

templates/normal_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1><i class="{{ icon }}"></i> {{ title }}</h1>
    {% if messages %}
        <div class="small callout alert">
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    <b>{{ error_message }}{{ form.errors }}</b>
    <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
        {% crispy form %}
    </form>
    <script type="text/javascript">
    {{ js | safe }}
    </script>
    <br/>
    {{ form.media }}
{% endblock %}

templates/place_list.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block content %}
    <h1><i class="fi-map"></i> Rechercher une localité</h1>
    <div class="secondary callout">
        <form action="" method="get">
            {{ filter.form.media }}
            <link rel="stylesheet" href="{% static 'css/select2-foundation-theme.min.css' %}">
            {{ filter.form.as_p }}
            <input class="button" type="submit"/>
        </form>
    </div>
{#    <script type="text/javascript">#}
{#        $(document).ready(function () {#}
{#            $(".listselect2").select2({#}
{#                placeholder: "Select a state",#}
{#                theme: "foundation"#}
{#            });#}
{#        });#}
{#    </script>#}
    {% render_table table %}
{% endblock %}

templates/place_map.html
{% extends 'base_leaflet.html' %}
{% load leaflet_tags %}
{% leaflet_js %}
{% leaflet_css %}
{% load geojson_tags %}
{% block content %}
    <h1><i class="fi-map"></i> Carte des localités</h1>
    <div id="progress">
        <div id="progress-bar"></div>
    </div>
    {% leaflet_map "main" %}
    <br/>
    <script type="text/javascript">
        var dataurl = '{% url "api:geodata_place" %}';
        window.addEventListener("map:init", function (event) {
            var markers = L.markerClusterGroup({chunkedLoading: true});

            var style_data = {
                radius: 8,
                fillColor: "#ff4c41",
                color: "#ddd",
                weight: 2,
                opacity: 1,
                fillOpacity: 0.8
            };


            var map = event.detail.map;
            // Download GeoJSON data with Ajax
            fetch(dataurl, {
                credentials: "include"
            })
                .then(function (resp) {
                    return resp.json();
                })
                .then(function (data) {
                    markers.addLayer(L.geoJson(data, {
                        onEachFeature: function onEachFeature(feature, layer) {
                            var props = feature.properties;
                            var content = `<h4>${props.pk} ∙ ${props.name}</h4>
{#        		                				<p>${props.municip}</p>#}
{#        		                				<p>${props.typloc}</p>#}
        		                				<p><a class="button" align="center" style="color:white;" href="/place/${props.pk}/detail" target="_blank" style="font-color:white"><strong>Fiche</strong></a></p>`;
                            layer.bindPopup(content);
                        }
                        ,
                        pointToLayer: function (feature, latlng) {
                            return L.circleMarker(latlng, style_data);
                        }
                    })).addTo(map);
                });
            map.fitBounds(markers.getBounds());
            map.addControl(new L.Control.Fullscreen());
        });
    </script>
{% endblock %}

templates/place_tilemap.html
{% extends 'base_leaflet.html' %}
{% load leaflet_tags %}
{% load geojson_tags %}
{% block content %}
    <h1><i class="fi-map"></i> Carte des localités</h1>
    {% leaflet_map "main" %}
    <br/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-tilelayer-geojson/1.0.4/TileLayer.GeoJSON.min.js"></script>
    <script src="js/leaflet/leaflet.ajax.min.js"></script>
    <script type="text/javascript">
        function popUp(f, l) {
            var out = [];
            if (f.properties) {
                for (key in f.properties) {
                    out.push("<b>" + key + "</b>: " + f.properties[key]);
                }
                l.bindPopup(out.join("<br />"));
            }
        }

        var territory_style = {
            "color": "#1779ba",
            "weight": 2,
            "opacity": 0.5
        };
        var location_style = {
            "clickable": true,
            "color": "#00D",
            "fillColor": "#00D",
            "weight": 1.0,
            "opacity": 0.3,
            "fillOpacity": 0.2
        };
        var location_hoverstyle = {
            "fillOpacity": 0.5
        };
        var data_territory = new L.GeoJSON.AJAX(["{% url "data_territory" %}"], {
            onEachFeature: popUp,
            style: territory_style
        }).addTo(map);
        var geojsonTileLayer = new L.TileLayer.GeoJSON('{% url "data_place_tile" %}', {
                clipTiles: true,
                unique: function (feature) {
                    return feature.id;
                }
            }, {
                style: style,
                onEachFeature: function (feature, layer) {
                    if (feature.properties) {
                        var popupString = '<div class="popup">';
                        for (var k in feature.properties) {
                            var v = feature.properties[k];
                            popupString += k + ': ' + v + '<br />';
                        }
                        popupString += '</div>';
                        layer.bindPopup(popupString);
                    }
                    if (!(layer instanceof L.Point)) {
                        layer.on('mouseover', function () {
                            layer.setStyle(location_hoverstyle);
                        });
                        layer.on('mouseout', function () {
                            layer.setStyle(location_style);
                        });
                    }
                }
            }
        );
        map.addLayer(geojsonTileLayer);

    </script>
{% endblock %}

templates/session_detail.html
{% extends 'base_fullwidth_leaflet.html' %}
{% load render_table from django_tables2 %}
{% load leaflet_tags %}
{% load geojson_tags %}
{% block content %}
    <h1><i class="{{ icon | safe }}"></i> {{ title | safe }}</h1>
    <p>
        <small>Session créée par <b>{{ object.created_by }}</b> le <b>{{ object.timestamp_create }}</b>
            {% if object.updated_by %}et
                mise à jour le <b>{{ object.timestamp_update }}</b> par <b>{{ object.updated_by }}</b>
                </small>{% endif %}
    </p>
    <div class="row">
        <div class="large-4 medium-6 small-12 columns">
            <div class="accordion" data-accordion>
                <li class="accordion-item is-active" data-accordion-item>
                    <a class="accordion-title">Informations principales</a>
                    <div class="accordion-content" data-tab-content>
                        <div class="row">
                            <div class="medium-6 small-12 columns">
                                <label>Nom de la session</label>
                                <div class="small callout">{{ object.name }}</div>
                            </div>
                            <div class="medium-6 small-12 columns">
                                <label>Méthode utilisée</label>
                                <div class="small callout">{{ object.contact.descr }}</div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="medium-4 small-6 columns">
                                <label>Début</label>
                                <div class="small callout">{{ object.date_start }}{% if object.time_start %} {{ object.time_start|time:"H:i"}}{% endif %}</div>
                            </div>
                            <div class="medium-4 small-6 columns">
                                <label>Date de fin</label>
                                <div class="small callout">{% if object.end_start %}{{ object.end_start }}{% if object.time_start %} {{ object.time_start|time:"H:i"}}{% endif %}{% else %}-{% endif %}</div>
                            </div>
                            <div class="medium-4 small-12 columns">
                                <label>Observateur principal</label>
                                <div class="small callout">{{ object.main_observer }}</div>
                            </div>
                        </div>
                        {% if object.is_confidential %}
                            <div class="row">
                                <div class="large-12 columns">
                                    <div class="small callout alert"><i class="fi-caution"></i> Cette session est
                                        confidentielle
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </li>
                <li class="accordion-item" data-accordion-item>
                    <a class="accordion-title">Localité</a>
                    <div class="accordion-content" data-tab-content>
                        <div class="row">
                            <div class="large-12 columns">
                                <div class="medium-6 small-12 columns">
                                    <label>Nom</label>
                                    <div class="small callout">
                                        <a href="{% url 'sights:place_detail' pk=object.place.id_place %}">{{ object.place.id_place }}
                                            / {{ object.place }}</a></div>
                                </div>
                                <div class="medium-6 small-12 columns">
                                    <label>Situation</label>
                                    <div class="small callout">{{ object.place.municipality.name }}
                                        ({{ object.place.territory.code }})
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                {% if object.comment %}
                    <li class="accordion-item" data-accordion-item>
                        <a class="accordion-title">Commentaire</a>
                        <div class="accordion-content" data-tab-content>
                            <div class="row">
                                <div class="large-12 columns">
                                    {{ object.comment|safe }}
                                </div>
                            </div>
                        </div>
                    </li>
                {% endif %}
            </div>
            <script type="text/javascript">
                var marker = {{ object.place.geom | geojsonfeature | safe }};

                function map_init_basic(map, options) {
                    L.geoJson(marker).addTo(map);
                    map.fitBounds(L.geoJson(marker).getBounds());
                    map.setZoom(15);
                };
            </script>
            <br/>
            <div class="button-group radius">
                <a title="Retour à la localité" class="button"
                   href="{% url 'sights:place_detail' pk=object.place.id_place %}"><i class="fi-arrow-left"></i> Retour</a>
                <a title="Modifier cette session" class="button warning"
                   href="{% url 'sights:session_update' pk=object.id_session %}"><i class="fi-page-edit"></i>
                    Modifier</a>
                <a title="Supprimer cette localité" class="button alert"
                   href="{% url 'sights:session_delete' pk=object.id_session %}"><i class="fi-trash"></i> Supprimer</a>
            </div>
        </div>

        <div class="large-8 medium-6 small-12 columns">
            <h3>
                <si class="{{ sightingicon | safe }}"></i> {{ sightingtitle | safe }}
            </h3>
            {% if sightingcount > 0 %}
                <div class="input-group">
                    <span class="input-group-label"><i class="fi-info"></i></span>
                    {% ifequal 1 sightingcount %}
                        <input class="input-group-field" type="text"
                               value="{{ sightingcount }} espèce" readonly>
                    {% else %}
                        <input class="input-group-field" type="text"
                               value="{{ sightingcount }} espèces" readonly>
                    {% endifequal %}
                    <div class="input-group-button">
                        <a href="{% url 'sights:sighting_create' pk=object.pk %}" class="button"
                           title="Créer une observation"><i class="fi-plus"></i></a>
                    </div>
                </div>
                {% if sightingcount > 0 %}

                    {% render_table sightingtable %}

                {% endif %}
            {% else %}
                <div class="input-group">
                    <span class="input-group-label"><i class="fi-info"></i></span>
                    <input class="input-group-field" type="text" value="Aucune observation" readonly>
                    <div class="input-group-button">
                        <a href="{% url 'sights:sighting_create' pk=object.pk %}" class="button"
                           title="Créer une observation"><i class="fi-plus"></i></a>
                    </div>
                </div>
            {% endif %}
        </div>


        <div class="large-8 medium-6 small-12 columns">
            <h3>
                <si class="{{ deviceicon }}"></i> {{ devicetitle }}
            </h3>
            {% if devicecount > 0 %}
                <div class="input-group">
                    <span class="input-group-label"><i class="fi-info"></i></span>
                    {% ifequal 1 devicecount %}
                        <input class="input-group-field" type="text"
                               value="{{ devicecount }} dispositif" readonly>
                    {% else %}
                        <input class="input-group-field" type="text"
                               value="{{ devicecount }} dispositifs" readonly>
                    {% endifequal %}
                    <div class="input-group-button">
                        <a href="{% url 'sights:device_create' pk=object.pk %}" class="button"
                           title="Créer un dispositif"><i class="fi-plus"></i></a>
                    </div>
                </div>
                {% render_table devicetable %}

            {% else %}
                <div class="input-group">
                    <span class="input-group-label"><i class="fi-info"></i></span>
                    <input class="input-group-field" type="text" value="Aucun dispositif" readonly>
                    <div class="input-group-button">
                        <a href="{% url 'sights:device_create' pk=object.pk %}" class="button"
                           title="Créer un dispositif"><i class="fi-plus"></i></a>
                    </div>
                </div>
            {% endif %}

        </div>

    </div>
    <br/> {% endblock %}

templates/table.html
{% extends 'base.html' %}
{% load render_table from django_tables2 %}
{% block content %}
    <h1><i class="{{ icon | safe }}"></i> {{ title | safe }}</h1>
    {% if count %}<div class="callout small">{{ counttitle }} : <b>{{ count }}</b></div>{% endif %}
    {% render_table table %}
    <script type="text/javascript">
    {{ js | safe }}
    </script>
    <br/>
{% endblock %}